### ISSUE TITLE
Flashing the bootloader & kernel

### ISSUE THREAD

**Issue by subashp** [Filipowicz251/mijia-1080P-hacks#15]
Hey Folks,

For whatever reason, the device I received was stuck at yellow/amber light when powered on. I opened up the hardware and decided to inspect whats going on underneath. I am not getting the boot logs (like in https://pastebin.com/raw/nt4GUAeF) and it now seems to me that the flash could be corrupt. Hence the processor is not able to loade the SPL which usually loads the u-boot and further on.

Does any of you know:
a) Where I can get the factory firmware
b) How to load the same into the flash?

There should be a way(because they would have done that during assembly) unless the SoC was preflashed by the supplier (which rarely happens) Any thoughts folks? I know this is very much different than the userspace hacks some of you do through the mmc card.

**Comment by willthrom** [comment]
normally, yellow is when no Wifi connection is available but the Camera should start playing an audio in Chinese stating that.  As far as I remember U-Boot or any other booting stage set the led to yellow.

Check the UART again, speed and connectors. 
Some one here messed with the FLASH but still the UART was working (at the end the booting process is somewhere else), In his case, U-BOOT was not able to load from the Flash.

To restore a flash without any software entrypoint is with a programmers. I opened a ticket at some point but I closed it because the person who bricked his camera didn´t continue investigating. https://github.com/Filipowicz251/mijia-1080P-hacks/issues/2

**Comment by subashp** [comment]
In the process I think I blew up the Tx pad on the board. Does anyone have access to the schematics which I can use to solder the Tx from some other component(resistors mostly)

**Comment by subashp** [comment]
@willthrom thanks to the link, I see that the SPI flash chip does have some activity during initial power on but nothing happens later. I dont know which stage of the bootloader lits up the yellow light, but you are right, it does. Probably it doesnt reach the uboot which initializes the UART from what I remember working in it long time ago. Looks like this will be another piece of electronic junk that will sit on my desk now.
