### ISSUE TITLE
Camera recording to SD card - video quality

### ISSUE THREAD

**Issue by nedimx** [Filipowicz251/mijia-1080P-hacks#16]
Hi,

I have two issues with recording on microsd card with this camera. 

1) RTSP
I didn't test 0.6 version, but 0.4 version.
Video is very slow and stuck on live preview, picture is very bad. Also problem is it is bad with RTSP and if I view on my MI Home app.. 
If wifi signal is worse, recorded video on sd card is worse too.

Maybe it's not a case in this 0.6 version, but I had to say this because of second problem.

![Image of Yaktocat](https://files.gitter.im/fang-hacks/Mijia-1080P/iPkr/picturee.png)

2) Stuck on video
I downgrade to version .139 (after I tried RTSP 4.0) and use standard MI Home firmware update.
I notice my video live and SD recorded have one issue. Video stuck like every 5 second for a second. 
I think this was not problem on this camera before downgrading to .139 version.
So in this case, video just stuck a little every 5 second (but quality is good), not like my 1) RTSP problem above.

**Comment by willthrom** [comment]
The rtsp server is still in beta but without the source code from Xiaomi and using the examples from the SDK the progress is quite slow. Besides noone else is working on this and I am very busy.

Regarding the performance, running Xiaomi streaming and the rtsp server will kill the camera.

You cannot downgrade to 139 because that is the latest one.  0019 is the version we can downgrade to install some parts of the tools, after that, upgrading to 139 it's safe, the tools will carry on working.

0.6 release have some options to disable Xiaomi processes, just play with them.
