### ISSUE TITLE
Can't connect to my network using MI home app

### ISSUE THREAD

**Issue by evilUrge** [Filipowicz251/mijia-1080P-hacks#66]
I've installed version 0.8.7 with 0099 firmware, the firmware was installed successfully and downgraded my camera (`tf_recovery.img` was renamed to `tf_recovery.img.bak` )

Because it wasn't connected yet to MI Home; I had to remove the SD card and connect it to my network via MI Home.

The camera was talking in Chinese as it should; but i never managed to pass the WIFI QR Code scanning
I suspect that the driver of the camera might be fucked and it doesn't taking a proper image (hence can't really scan a simple QR)

Tried all the firmwares mentioned in [Recovery Debrick](https://github.com/Filipowicz251/mijia-1080P-hacks/wiki/Recovery---Debrick); but same result.|

Any idea on how can I perhaps make the camera connect to the network without using MI Home\QR scanning =|
(or revert to factory version; this camera used to work)

**Comment by tobbegutt** [comment]
try connecting using other method as it will be using Bluetooth. i have experienced this myself.



Sendt fra min MI MAX 3
Den Gilad Maoz <notifications@github.com>, skrev 30. okt. 2019 17:56:

I've installed version 0.8.7 with 0099 firmware, the firmware was installed successfully and downgraded my camera (tf_recovery.img was renamed to tf_recovery.img.bak )

Because it wasn't connected yet to MI Home; I had to remove the SD card and connect it to my network via MI Home.

The camera was talking in Chinese as it should; but i never managed to pass the WIFI QR Code scanning
I suspect that the driver of the camera might be fucked and it doesn't taking a proper image (hence can't really scan a simple QR)

Tried all the firmwares mentioned in Recovery Debrick<https://github.com/Filipowicz251/mijia-1080P-hacks/wiki/Recovery---Debrick>; but same result.|

Any idea on how can I perhaps make the camera connect to the network without using MI Home\QR scanning =|
(or revert to factory version; this camera used to work)

**Comment by evilUrge** [comment]
Yeah I read about it before; but because I couldn't find "Pair using bluetooth" in MI home I thought it's not possible.


Just downgraded to [4.0.11](https://www.apkmirror.com/apk/xiaomi-inc/mihome/mihome-4-0-11-release/) and it worked!!!!! =D

Thanks @tobbegutt

**Comment by lotech** [comment]
Yeah I also had issues - and there is indeed a hidden connect via Bluetooth option - connected on my Android phone with MI Home 4.0.11. When I did it up and going again the image was corrupted in MiHome. I've obviously borked the sensor information. Annoying as I've battled my way to getting SSH working - although the camera just makes an AP and a new network.
